<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ProjectProgressUpdate extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'address.*.freelease' => 'required',
            'address.*.area' => 'required|numeric|min:0',
            'address.*.acqusition' => 'required',
            'barea'        => 'required|numeric|min:0',
            'bStartDate'   => 'required',
            'bCompDate'    => 'required',
            'bRemarks'     => 'required',
            'oarea'        => 'required|numeric|min:0',
            'oStartDate'   => 'required',
            'oCompDate'    => 'required',
            'oRemarks'     => 'required',
            'carea'        => 'required|numeric|min:0',
            'cStartDate'   => 'required',
            'cCompDate'    => 'required',
            'cRemarks'     => 'required',
            'uarea'        => 'required|numeric|min:0',
            'uStartDate'   => 'required',
            'uCompDate'    => 'required',
            'uRemarks'     => 'required',
            'parea'        => 'required|numeric|min:0',
            'pStartDate'   => 'required',
            'pCompDate'    => 'required',
            'pRemarks'     => 'required',
            'larea'        => 'required|numeric|min:0',
            'lStartDate'   => 'required',
            'lCompDate'    => 'required',
            'lRemarks'     => 'required',
            'rarea'        => 'required|numeric|min:0',
            'rStartDate'   => 'required',
            'rCompDate'    => 'required',
            'rRemarks'     => 'required',
            'earea'        => 'required|numeric|min:0',
            'eStartDate'   => 'required',
            'eCompDate'    => 'required',
            'eRemarks'     => 'required',
            'sarea'        => 'required|numeric|min:0',
            'sStartDate'   => 'required',
            'sCompDate'    => 'required',
            'sRemarks'     => 'required',
            'harea'=> 'required|numeric|min:0',
            'hStartDate'=> 'required',
            'hCompDate'=> 'required',
            'hRemarks'=> 'required',
            'warea'=> 'required|numeric|min:0',
            'wStartDate'=> 'required',
            'wCompDate'=> 'required',
            'wRemarks'=> 'required',
            'rwarea'=> 'required|numeric|min:0',
            'rwStartDate'=> 'required',
            'rwCompDate'=> 'required',
            'rwRemarks'=> 'required',
            'swarea'=> 'required|numeric|min:0',
            'swStartDate'=> 'required',
            'swCompDate'=> 'required',
            'swRemarks'=> 'required',
            'dmwarea'=> 'required|numeric|min:0',
            'dmwStartDate'=> 'required',
            'dmwCompDate'=> 'required',
            'dmwRemarks'=> 'required',
	    'stmarea'=> 'required|numeric|min:0',
            'stmStartDate'=> 'required',
            'stmCompDate'=> 'required',
            'stmRemarks'=> 'required',
            'caarea'=> 'required|numeric|min:0',
            'caStartDate'=> 'required',
            'caCompDate'=> 'required',
            'caRemarks'=> 'required',
            'coarea'=> 'required|numeric|min:0',
            'coStartDate'=> 'required',
            'coCompDate'=> 'required',
            'coRemarks'=> 'required',
            'boarea'=> 'required|numeric|min:0',
            'boStartDate'=> 'required',
            'boCompDate'=> 'required',
            'boRemarks'=> 'required',
            'pgarea'=> 'required|numeric|min:0',
            'pgStartDate'=> 'required',
            'pgCompDate'=> 'required',
            'pgRemarks'=> 'required',
            'starea'=> 'required|numeric|min:0',
            'stStartDate'=> 'required',
            'stCompDate'=> 'required',
            'stRemarks'=> 'required',
            'misarea'=> 'required|numeric|min:0',
            'misStartDate'=> 'required',
            'misCompDate'=> 'required',
            'misRemarks'=> 'required',
            'bprevExpense'=> 'required|numeric|min:0',
            'bcurrExpense'=> 'required|numeric|min:0',
            'pprevExpense'=> 'required|numeric|min:0',
            'pcurrExpense'=> 'required|numeric|min:0',
            'lprevExpense'=> 'required|numeric|min:0',
            'lcurrExpense'=> 'required|numeric|min:0',
            'eprevExpense'=> 'required|numeric|min:0',
            'ecurrExpense'=> 'required|numeric|min:0',
            'rdprevExpense'=> 'required|numeric|min:0',
            'rdcurrExpense'=> 'required|numeric|min:0',
            'efprevExpense'=> 'required|numeric|min:0',
            'efcurrExpense'=> 'required|numeric|min:0',
            'solidprevExpense'=> 'required|numeric|min:0',
            'solidcurrExpense'=> 'required|numeric|min:0',
            'hprevExpense'=> 'required|numeric|min:0',
            'hcurrExpense'=> 'required|numeric|min:0',
            'wsprevExpense'=> 'required|numeric|min:0',
            'wscurrExpense'=> 'required|numeric|min:0',
            'rwprevExpense'=> 'required|numeric|min:0',
            'rwcurrExpense'=> 'required|numeric|min:0',
            'dmprevExpense'=> 'required|numeric|min:0',
            'dmcurrExpense'=> 'required|numeric|min:0',
            'caprevExpense'=> 'required|numeric|min:0',
            'cacurrExpense'=> 'required|numeric|min:0',
            'coprevExpense'=> 'required|numeric|min:0',
            'cocurrExpense'=> 'required|numeric|min:0',
            'boprevExpense'=> 'required|numeric|min:0',
            'bocurrExpense'=> 'required|numeric|min:0',
            'poprevExpense'=> 'required|numeric|min:0',
            'pocurrExpense'=> 'required|numeric|min:0',
            'stprevExpense'=> 'required|numeric|min:0',
            'stcurrExpense'=> 'required|numeric|min:0',
	    'stmprevExpense'=> 'required|numeric|min:0',
            'stmcurrExpense'=> 'required|numeric|min:0',
            'misprevExpense'=> 'required|numeric|min:0',
            'miscurrExpense'=> 'required|numeric|min:0',
            'totprevExpense'=> 'required|numeric|min:0',
            'totcurrExpense'=> 'required|numeric|min:0',
        ];
    }


    public function messages()
    {
        return [
            'address.*.freelease.required' => 'This field is required',
            'address.*.area.required' => 'This field is required',
            'address.*.acqusition.required' => 'This field is required',
            'barea.required'        => 'This field is required',
            'bStartDate.required'   => 'This field is required',
            'bCompDate.required'    => 'This field is required',
            'bRemarks.required'     => 'This field is required',
            'oarea.required'        => 'This field is required',
            'oStartDate.required'   => 'This field is required',
            'oCompDate.required'    => 'This field is required',
            'oRemarks.required'     => 'This field is required',
            'carea.required'        => 'This field is required',
            'cStartDate.required'   => 'This field is required',
            'cCompDate.required'    => 'This field is required',
            'cRemarks.required'     => 'This field is required',
            'uarea.required'        => 'This field is required',
            'uStartDate.required'   => 'This field is required',
            'uCompDate.required'    => 'This field is required',
            'uRemarks.required'     => 'This field is required',
            'parea.required'        => 'This field is required',
            'pStartDate.required'   => 'This field is required',
            'pCompDate.required'    => 'This field is required',
            'pRemarks.required'     => 'This field is required',
            'larea.required'        => 'This field is required',
            'lStartDate.required'   => 'This field is required',
            'lCompDate.required'    => 'This field is required',
            'lRemarks.required'     => 'This field is required',
            'rarea.required'        => 'This field is required',
            'rStartDate.required'   => 'This field is required',
            'rCompDate.required'    => 'This field is required',
            'rRemarks.required'     => 'This field is required',
            'earea.required'        => 'This field is required',
            'eStartDate.required'   => 'This field is required',
            'eCompDate.required'    => 'This field is required',
            'eRemarks.required'     => 'This field is required',
            'sarea.required'        => 'This field is required',
            'sStartDate.required'   => 'This field is required',
            'sCompDate.required'    => 'This field is required',
            'sRemarks.required'     => 'This field is required',
            'harea.required'        => 'This field is required',
            'hStartDate.required'=> 'This field is required',
            'hCompDate.required'=> 'This field is required',
            'hRemarks.required'=> 'This field is required',
            'warea.required'        => 'This field is required',
            'wStartDate.required'=> 'This field is required',
            'wCompDate.required'=> 'This field is required',
            'wRemarks.required'=> 'This field is required',
            'rwarea.required'        => 'This field is required',
            'rwStartDate.required'=> 'This field is required',
            'rwCompDate.required'=> 'This field is required',
            'rwRemarks.required'=> 'This field is required',
            'swarea.required'        => 'This field is required',
            'swStartDate.required'=> 'This field is required',
            'swCompDate.required'=> 'This field is required',
            'swRemarks.required'=> 'This field is required',
            'dmwarea.required'        => 'This field is required',
            'dmwStartDate.required'=> 'This field is required',
            'dmwCompDate.required'=> 'This field is required',
            'dmwRemarks.required'=> 'This field is required',
	    'stmarea.required'        => 'This field is required',
            'stmStartDate.required'=> 'This field is required',
            'stmCompDate.required'=> 'This field is required',
            'stmRemarks.required'=> 'This field is required',
            'caarea.required'        => 'This field is required',
            'caStartDate.required'=> 'This field is required',
            'caCompDate.required'=> 'This field is required',
            'caRemarks.required'=> 'This field is required',
            'coarea.required'        => 'This field is required',
            'coStartDate.required'=> 'This field is required',
            'coCompDate.required'=> 'This field is required',
            'coRemarks.required'=> 'This field is required',
            'boarea.required'        => 'This field is required',
            'boStartDate.required'=> 'This field is required',
            'boCompDate.required'=> 'This field is required',
            'boRemarks.required'=> 'This field is required',
            'pgarea.required'        => 'This field is required',
            'pgStartDate.required'=> 'This field is required',
            'pgCompDate.required'=> 'This field is required',
            'pgRemarks.required'=> 'This field is required',
            'starea.required'        => 'This field is required',
            'stStartDate.required'=> 'This field is required',
            'stCompDate.required'=> 'This field is required',
            'stRemarks.required'=> 'This field is required',
            'misarea.required'        => 'This field is required',
            'misStartDate.required'=> 'This field is required',
            'misCompDate.required'=> 'This field is required',
            'misRemarks.required'=> 'This field is required',
            'bprevExpense.required'=> 'This field is required',
            'bcurrExpense.required'=> 'This field is required',
            'pprevExpense.required'=> 'This field is required',
            'pcurrExpense.required'=> 'This field is required',
            'lprevExpense.required'=> 'This field is required',
            'lcurrExpense.required'=> 'This field is required',
            'eprevExpense.required'=> 'This field is required',
            'ecurrExpense.required'=> 'This field is required',
            'rdprevExpense.required'=> 'This field is required',
            'rdcurrExpense.required'=> 'This field is required',
            'efprevExpense.required'=> 'This field is required',
            'efcurrExpense.required'=> 'This field is required',
            'solidprevExpense.required'=> 'This field is required',
            'solidcurrExpense.required'=> 'This field is required',
            'hprevExpense.required'=> 'This field is required',
            'hcurrExpense.required'=> 'This field is required',
            'wsprevExpense.required'=> 'This field is required',
            'wscurrExpense.required'=> 'This field is required',
            'rwprevExpense.required'=> 'This field is required',
            'rwcurrExpense.required'=> 'This field is required',
            'dmprevExpense.required'=> 'This field is required',
            'dmcurrExpense.required'=> 'This field is required',
            'caprevExpense.required'=> 'This field is required',
            'cacurrExpense.required'=> 'This field is required',
            'coprevExpense.required'=> 'This field is required',
            'cocurrExpense.required'=> 'This field is required',
            'boprevExpense.required'=> 'This field is required',
            'bocurrExpense.required'=> 'This field is required',
            'poprevExpense.required'=> 'This field is required',
            'pocurrExpense.required'=> 'This field is required',
            'stmprevExpense.required'=> 'This field is required',
            'stmcurrExpense.required'=> 'This field is required',
	    'stprevExpense.required'=> 'This field is required',
            'stcurrExpense.required'=> 'This field is required',
            'misprevExpense.required'=> 'This field is required',
            'miscurrExpense.required'=> 'This field is required',
            'totprevExpense.required'=> 'This field is required',
            'totcurrExpense.required'=> 'This field is required',
        ];
    }
}
