<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RevenueStore extends FormRequest
{
    
    public function authorize()
    {
        return false;
    }
    public function rules()
    {
        return [
            'gcDomPrevQuantity'         => 'required|numeric|min:0',
            'gcDomPrevSales'            => 'required|numeric|min:0',
            'gcDomCurrQuantity'         => 'required|numeric|min:0',
            'gcDomCurrSales'            => 'required|numeric|min:0',
            'gcExpPrevQuantity'         => 'required|numeric|min:0',
            'gcExpPrevSales'            => 'required|numeric|min:0',
            'gcExpCurrQuantity'         => 'required|numeric|min:0',
            'gcExpCurrSales'            => 'required|numeric|min:0',
            'gcCapPrevQuantity'         => 'required|numeric|min:0',
            'gcCapPrevSales'            => 'required|numeric|min:0',
            'gcCapCurrQuantity'         => 'required|numeric|min:0',
            'gcCapCurrSales'            => 'required|numeric|min:0',
            'gcTotPrevQuantity'         => 'required|numeric|min:0',
            'gcTotPrevSales'            => 'required|numeric|min:0',
            'gcTotCurrQuantity'         => 'required|numeric|min:0',
            'gcTotCurrSales'            => 'required|numeric|min:0',
            'ecDomPrevQuantity'         => 'required|numeric|min:0',
            'ecDomPrevSales'            => 'required|numeric|min:0',
            'ecDomCurrQuantity'         => 'required|numeric|min:0',
            'ecDomCurrSales'            => 'required|numeric|min:0',
            'ecExpPrevQuantity'         => 'required|numeric|min:0',
            'ecExpPrevSales'            => 'required|numeric|min:0',
            'ecExpCurrQuantity'         => 'required|numeric|min:0',
            'ecExpCurrSales'            => 'required|numeric|min:0',
            'ecCapPrevQuantity'         => 'required|numeric|min:0',
            'ecCapPrevSales'            => 'required|numeric|min:0',
            'ecCapCurrQuantity'         => 'required|numeric|min:0',
            'ecCapCurrSales'            => 'required|numeric|min:0',
            'ecTotPrevQuantity'         => 'required|numeric|min:0',
            'ecTotPrevSales'            => 'required|numeric|min:0',
            'ecTotCurrQuantity'         => 'required|numeric|min:0',
            'ecTotCurrSales'            => 'required|numeric|min:0',
            'otDomPrevQuantity'         => 'required|numeric|min:0',
            'otDomPrevSales'            => 'required|numeric|min:0',
            'otDomCurrQuantity'         => 'required|numeric|min:0',
            'otDomCurrSales'            => 'required|numeric|min:0',
            'otExpPrevQuantity'         => 'required|numeric|min:0',
            'otExpPrevSales'            => 'required|numeric|min:0',
            'otExpCurrQuantity'         => 'required|numeric|min:0',
            'otExpCurrSales'            => 'required|numeric|min:0',
            'otCapPrevQuantity'         => 'required|numeric|min:0',
            'otCapPrevSales'            => 'required|numeric|min:0',
            'otCapCurrQuantity'         => 'required|numeric|min:0',
            'otCapCurrSales'            => 'required|numeric|min:0',
            'otTotPrevQuantity'         => 'required|numeric|min:0',
            'otTotPrevSales'            => 'required|numeric|min:0',
            'otTotCurrQuantity'         => 'required|numeric|min:0',
            'otTotCurrSales'            => 'required|numeric|min:0',
            'otherPrevQuantity'         => 'required|numeric|min:0',
            'otherPrevSales'            => 'required|numeric|min:0',
            'otherCurrQuantity'         => 'required|numeric|min:0',
            'otherCurrSales'            => 'required|numeric|min:0',
            'totPrevQuantity'           => 'required|numeric|min:0',
            'totPrevSales'              => 'required|numeric|min:0',
            'totCurrQuantity'           => 'required|numeric|min:0',
            'totCurrSales'              => 'required|numeric|min:0',

            'laborPrevNo'               => 'required|numeric|min:0',
            'laborCurrNo'               => 'required|numeric|min:0',
            'empPrevNo'                 => 'required|numeric|min:0',
            'empCurrNo'                 => 'required|numeric|min:0',
            'conPrevNo'                 => 'required|numeric|min:0',
            'conCurrNo'                 => 'required|numeric|min:0',
            'appPrevNo'                 => 'required|numeric|min:0',
            'appCurrNo'                 => 'required|numeric|min:0',
            'totPrevNo'                 => 'required|numeric|min:0',
            'totCurrNo'                 => 'required|numeric|min:0',

            'EPprevquant'               => 'required|numeric|min:0',
            'EPprevsales'               => 'required|numeric|min:0',
            'EPprevamount'              => 'required|numeric|min:0',
            'EPcurrquant'               => 'required|numeric|min:0',
            'EPcurrsales'               => 'required|numeric|min:0',
            'EPcurramount'              => 'required|numeric|min:0',
            'totConprevquant'           => 'required|numeric|min:0',
            'totConprevamount'          => 'required|numeric|min:0|not_in:0',
            'totConcurrquant'           => 'required|numeric|min:0',
            'totConcurramount'          => 'required|numeric|min:0|not_in:0',
            'matprevquant'              => 'required|numeric|min:0',
            'matprevamount'             => 'required|numeric|min:0',
            'matcurrquant'              => 'required|numeric|min:0',
            'matcurramount'             => 'required|numeric|min:0',
            'serprevquant'              => 'required|numeric|min:0',
            'serprevamount'             => 'required|numeric|min:0',
            'sercurrquant'              => 'required|numeric|min:0',
            'sercurramount'             => 'required|numeric|min:0',
            'prevDVATotal'           => 'required|numeric|min:0',
            'currDVATotal'           => 'required|numeric|min:0',


            'mattprev.*.particulars'    => 'required',
            'mattprev.*.country'        => 'required|regex:/^[a-zA-Z]+$/u',
            'mattprev.*.quantity'       => 'required|numeric|min:0',
            'mattprev.*.amount'         => 'required|numeric|min:0',

            'serrprev.*.particulars'    => 'required',
            'serrprev.*.country'        => 'required|regex:/^[a-zA-Z]+$/u',
            'serrprev.*.quantity'       => 'required|numeric|min:0',
            'serrprev.*.amount'         => 'required|numeric|min:0',

            'mattcurr.*.particulars'    => 'required',
            'mattcurr.*.country'        => 'required|regex:/^[a-zA-Z]+$/u',
            'mattcurr.*.quantity'       => 'required|numeric|min:0',
            'mattcurr.*.amount'         => 'required|numeric|min:0',

            'serrcurr.*.particulars'    => 'required',
            'serrcurr.*.country'        => 'required|regex:/^[a-zA-Z]+$/u',
            'serrcurr.*.quantity'       => 'required|numeric|min:0',
            'serrcurr.*.amount'         => 'required|numeric|min:0',

            'mattprevtot'               => 'required|numeric|numeric|min:0',
            'serrprevtot'               => 'required|numeric|numeric|min:0', 
            'mattcurrtot'               => 'required|numeric|numeric|min:0', 
            'serrcurrtot'               => 'required|numeric|numeric|min:0', 
        ];
    }

    public function messages()
    {
        return [
            'gcDomPrevQuantity.required'         => 'This field is required',
            'gcDomPrevSales.required'            => 'This field is required',
            'gcDomCurrQuantity.required'         => 'This field is required',
            'gcDomCurrSales.required'            => 'This field is required',
            'gcExpPrevQuantity.required'         => 'This field is required',
            'gcExpPrevSales.required'            => 'This field is required',
            'gcExpCurrQuantity.required'         => 'This field is required',
            'gcExpCurrSales.required'            => 'This field is required',
            'gcCapPrevQuantity.required'         => 'This field is required',
            'gcCapPrevSales.required'            => 'This field is required',
            'gcCapCurrQuantity.required'         => 'This field is required',
            'gcCapCurrSales.required'            => 'This field is required',
            'gcTotPrevQuantity.required'         => 'This field is required',
            'gcTotPrevSales.required'            => 'This field is required',
            'gcTotCurrQuantity.required'         => 'This field is required',
            'gcTotCurrSales.required'            => 'This field is required',
            'ecDomPrevQuantity.required'         => 'This field is required',
            'ecDomPrevSales.required'            => 'This field is required',
            'ecDomCurrQuantity.required'         => 'This field is required',
            'ecDomCurrSales.required'            => 'This field is required',
            'ecExpPrevQuantity.required'         => 'This field is required',
            'ecExpPrevSales.required'            => 'This field is required',
            'ecExpCurrQuantity.required'         => 'This field is required',
            'ecExpCurrSales.required'            => 'This field is required',
            'ecCapPrevQuantity.required'         => 'This field is required',
            'ecCapPrevSales.required'            => 'This field is required',
            'ecCapCurrQuantity.required'         => 'This field is required',
            'ecCapCurrSales.required'            => 'This field is required',
            'ecTotPrevQuantity.required'         => 'This field is required',
            'ecTotPrevSales.required'            => 'This field is required',
            'ecTotCurrQuantity.required'         => 'This field is required',
            'ecTotCurrSales.required'            => 'This field is required',
            'otDomPrevQuantity.required'         => 'This field is required',
            'otDomPrevSales.required'            => 'This field is required',
            'otDomCurrQuantity.required'         => 'This field is required',
            'otDomCurrSales.required'            => 'This field is required',
            'otExpPrevQuantity.required'         => 'This field is required',
            'otExpPrevSales.required'            => 'This field is required',
            'otExpCurrQuantity.required'         => 'This field is required',
            'otExpCurrSales.required'            => 'This field is required',
            'otCapPrevQuantity.required'         => 'This field is required',
            'otCapPrevSales.required'            => 'This field is required',
            'otCapCurrQuantity.required'         => 'This field is required',
            'otCapCurrSales.required'            => 'This field is required',
            'otTotPrevQuantity.required'         => 'This field is required',
            'otTotPrevSales.required'            => 'This field is required',
            'otTotCurrQuantity.required'         => 'This field is required',
            'otTotCurrSales.required'            => 'This field is required',
            'otherPrevQuantity.required'         => 'This field is required',
            'otherPrevSales.required'            => 'This field is required',
            'otherCurrQuantity.required'         => 'This field is required',
            'otherCurrSales.required'            => 'This field is required',
            'totPrevQuantity.required'           => 'This field is required',
            'totPrevSales.required'              => 'This field is required',
            'totCurrQuantity.required'           => 'This field is required',
            'totCurrSales.required'              => 'This field is required',

            'laborPrevNo.required'               => 'This field is required',
            'laborCurrNo.required'               => 'This field is required',
            'empPrevNo.required'                 => 'This field is required',
            'empCurrNo.required'                 => 'This field is required',
            'conPrevNo.required'                 => 'This field is required',
            'conCurrNo.required'                 => 'This field is required',
            'appPrevNo.required'                 => 'This field is required',
            'appCurrNo.required'                 => 'This field is required',
            'totPrevNo.required'                 => 'This field is required',
            'totCurrNo.required'                 => 'This field is required',

            'EPprevquant.required'               => 'This field is required',
            'EPprevsales.required'               => 'This field is required',
            'EPprevamount.required'              => 'This field is required',
            'EPcurrquant.required'               => 'This field is required',
            'EPcurrsales.required'               => 'This field is required',
            'EPcurramount.required'              => 'This field is required',
            'totConprevquant.required'           => 'This field is required',
            'totConprevamount.required'          => 'This field is required',
            'totConcurrquant.required'           => 'This field is required',
            'totConcurramount.required'          => 'This field is required',
            'matprevquant.required'              => 'This field is required',
            'matprevamount.required'             => 'This field is required',
            'matcurrquant.required'              => 'This field is required',
            'matcurramount.required'             => 'This field is required',
            'serprevquant.required'              => 'This field is required',
            'serprevamount.required'             => 'This field is required',
            'sercurrquant.required'              => 'This field is required',
            'sercurramount.required'             => 'This field is required',
            'prevDVATotal.required'           => 'This field is required',
            'currDVATotal.required'           => 'This field is required',


            'mattprev.*.particulars.required'    => 'This field is required',
            'mattprev.*.country.required'        => 'This field is required',
            'mattprev.*.quantity.required'       => 'This field is required',
            'mattprev.*.amount.required'         => 'This field is required',

            'serrprev.*.particulars.required'    => 'This field is required',
            'serrprev.*.country.required'        => 'This field is required',
            'serrprev.*.quantity.required'       => 'This field is required',
            'serrprev.*.amount.required'         => 'This field is required',

            'mattcurr.*.particulars.required'    => 'This field is required',
            'mattcurr.*.country.required'        => 'This field is required',
            'mattcurr.*.quantity.required'       => 'This field is required',
            'mattcurr.*.amount.required'         => 'This field is required',

            'serrcurr.*.particulars.required'    => 'This field is required',
            'serrcurr.*.country.required'        => 'This field is required',
            'serrcurr.*.quantity.required'       => 'This field is required',
            'serrcurr.*.amount.required'         => 'This field is required',

            'mattprevtot.required'               => 'This field is required|numeric',
            'serrprevtot.required'               => 'This field is required|numeric', 
            'mattcurrtot.required'               => 'This field is required|numeric', 
            'serrcurrtot.required'               => 'This field is required|numeric', 
        ];
    }
}
