<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Financials extends Model
{
    protected $fillable = [
        'id',
        'app_id',
        'phar_dom_17',
        'phar_dom_18',
        'phar_dom_19',
        'phar_exp_17',
        'phar_exp_18',
        'phar_exp_19',
        'oth_dom_17',
        'oth_dom_18',
        'oth_dom_19',
        'oth_exp_17',
        'oth_exp_18',
        'oth_exp_19',
        'oth_inc_17',
        'oth_inc_18',
        'oth_inc_19',
        'tot_rev_17',
        'tot_rev_18',
        'tot_rev_19',
        'pbt17',
        'pbt18',
        'pbt19',
        'pat17',
        'pat18',
        'pat19',
        'sh_cap_17',
        'sh_cap_18',
        'sh_cap_19',
        'eq_prom_17',
        'eq_prom_18',
        'eq_prom_19',
        'eq_ind_17',
        'eq_ind_18',
        'eq_ind_19',
        'eq_frn_17',
        'eq_frn_18',
        'eq_frn_19',
        'eq_mult_17',
        'eq_mult_18',
        'eq_mult_19',
        'eq_bank_17',
        'eq_bank_18',
        'eq_bank_19',
        'int_acc_17',
        'int_acc_18',
        'int_acc_19',
        'ln_prom_17',
        'ln_prom_18',
        'ln_prom_19',
        'ln_ind_17',
        'ln_ind_18',
        'ln_ind_19',
        'ln_frn_17',
        'ln_frn_18',
        'ln_frn_19',
        'ln_mult_17',
        'ln_mult_18',
        'ln_mult_19',
        'ln_bank_17',
        'ln_bank_18',
        'ln_bank_19',
        'gr_ind_17',
        'gr_ind_18',
        'gr_ind_19',
        'gr_frn_17',
        'gr_frn_18',
        'gr_frn_19',
        'rnd_unit',
        'rnd_rcnz',
        'rnd_inv_17',
        'rnd_inv_18',
        'rnd_inv_19',
        'rnd_achv',
        'cap_17',
        'cap_18',
        'cap_19',
        'sof_17',
        'sof_18',
        'sof_19'
    ];

    public function application()
    {
        return $this->belongsTo('App\ApplicationMast', 'app_id');
    }
}
